[phases.setup]
# Liste des paquets nix à installer si besoin (laisser vide si pas nécessaire)
nixPkgs = ["maven", "openjdk"]

[phases.build]
cmds = [
  "cd core && mvn clean package -DskipTests"
]

[start]
cmd = "java -Dserver.port=$PORT -jar core/target/demo-0.0.1-SNAPSHOT.jar"
